// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index(Props) {
  return React.createElement("div", {
              className: "flex h-20 justify-center items-center text-2xl"
            }, React.createElement("div", {
                  className: "i-bi-star"
                }), "Hello, world!");
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
